// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "/|zzwiULSnD#FR61UZ7o":
            case "Bojovnik":return img`
........................
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef...77.......
.ffffee2222ef.777.......
.fe222ffffe2f7777.......
fffffffeeeff7777........
ffe44ebf44e7777.........
fee4d41fdde777..........
.feee4ddded777..........
..ffee44e4dde...........
...f222244ee............
...f2222e2f.............
...f444455f.............
....ffffff..............
.....fff................
........................
........................
........................
........................
........................
........................
........................
`;
            case "Ekf7o@+HAxfmxt(sptuE":
            case "Poklad":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . d . . . . . . . 
. . . . . c . b d b . c . . . . 
. . . b . . c b d b c . . b . . 
. . . . b b c 5 5 5 c b b . . . 
. . c . b 5 5 5 1 5 5 5 b . c . 
. . . c c 5 5 5 1 5 5 5 c c . . 
. . b b 5 5 5 1 1 1 5 5 5 b b . 
. d d d 5 1 1 1 5 1 1 1 5 d d d 
. . b b 5 5 5 1 1 1 5 5 5 b b . 
. . . c c 5 5 5 1 5 5 5 c c . . 
. . c . b 5 5 5 1 5 5 5 b . c . 
. . . . b b c 5 5 5 c b b . . . 
. . . b . . c b d b c . . b . . 
. . . . . c . b d b . c . . . . 
. . . . . . . . d . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
